### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/maestro#19]
Without any test coverage it is relatively likely that something will break as the project moves forward. However, testing some modules such as Twilio would be incredibly difficult. And besides modules some files like hub.go would also be hard to test.

@zachlatta Any suggestions and advice would be appreciated.

**Comment by zachlatta** [comment]
Any specifics roadblocks you forsee running into when writing tests? For
Twilio we could mock their API.

On Fri, Jul 10, 2015 at 10:02 PM, Benjamin Landers <notifications@github.com

**Comment by TheThirdOne** [comment]
For testing Twilio, mocking their api would likely be as likely or more likely to fail than the Twilio module. As a result, testing based on that would be testing the mock more than the module. 

Hub.go will be difficult simply because of how interconnected it is. Though it would be possible to make mocks for each of its dependencies. 

I have no clue how to test conn.go or handler.go to make sure they are working properly, though the chance something unusual, will happen in those files is minuscule  compared to hub.go or the modules.

**Comment by zachlatta** [comment]
What are some of the specific things that may break with the Twilio module
that we want to test for?

**Comment by TheThirdOne** [comment]
Making sure callbacks are handled correctly under multi-user conditions. And just generally unit testing. (Which could probably be covered by Twilio testing api)

**Comment by zachlatta** [comment]
How complex would writing a mock for that be? Sounds like something a mock
would work fine for.

**Comment by TheThirdOne** [comment]
A proper mock that would give me confidence would be very hard to make.

**Comment by zachlatta** [comment]
Hmm – it doesn't sound overwhelmingly difficult to me. Wouldn't it just be
calling the right endpoints and mocking a few users?

Happy to work together on this.

**Comment by TheThirdOne** [comment]
What do you mean by `calling the right endpoints`?

**Comment by zachlatta** [comment]
Something along the lines of
http://keighl.com/post/mocking-http-responses-in-golang/ or something
analogous to how Google's `go-github` library does testing (see
https://github.com/google/go-github/blob/master/github/gitignore_test.go
for an example).

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us/>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jkwok91** [comment]
Closing because this repo is being deprecated
