### ISSUE TITLE
Add more apis

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/maestro#2]
Feel free to comment apis you would like to see added.

**Comment by zachlatta** [comment]
Just brainstorming here:

* Twilio
* Twitter
* GitHub
* Hacker News
* Snapchat (would have to reverse engineer it, not sure how okay this would be)

**Comment by zachlatta** [comment]
If they have an API, we should totally add http://www.theverge.com/2015/6/4/8725665/tumblr-gif-search-launches.

**Comment by TheThirdOne** [comment]
Instagram's real time api is pretty cool. https://instagram.com/developer/realtime/

**Comment by TheThirdOne** [comment]
Souncloud or Spotify

**Comment by zachlatta** [comment]
Hacker News

On Mon, Aug 17, 2015 at 11:27 PM, Benjamin Landers <notifications@github.com
> wrote:

> Souncloud or Spotify
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/maestro/issues/2#issuecomment-132088468>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jkwok91** [comment]
Closing because this repo is being deprecated (https://github.com/hackclub/maestro/issues/29)
