### ISSUE TITLE
Node module

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/maestro#20]

**Comment by zachlatta** [comment]
Is this to make Maestro compatible with Node?

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us/>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by TheThirdOne** [comment]
Yes

**Comment by jkwok91** [comment]
Closing because this repo is being deprecated
