### ISSUE TITLE
Add an error channel

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/maestro#27]
Currently internal errors all only logged. A channel to collect errors would allow hub to send those to the user and allow tests to test cases where the code should error.

**Comment by TheThirdOne** [comment]
@zachlatta should this actually be done with a channel or should it be linked into logrus (make a hook that echos errors to users if an CommandID is in the log).

**Comment by zachlatta** [comment]
I'd have a channel that pipes to both the user and to Logrus.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by TheThirdOne** [comment]
I think I may not have been clear enough. For any error that hit the channel, Logrus should have already been called. So it wouldn't really make sense to pipe it to Logrus.

To clarify:
```
Option 1 (raw error channel) 
module => Logrus
      L=> error channel => Hub => client

Option 2 (Logrus hook)
module => Logrus => error channel => Hub => client

Option 3 (error channel that logs)s
module =>  error channel => Hub => client
                               L=> Logrus
```

Option | Pro | Con
---------|------|------
1    | simple implementation in hub <br> easy testing modules| messy passing the error channel around <br/>messy implementation in modules
2 | very clean implementation in modules | awkward design 
3 | easy testing modules |  messy passing the error channel around <br/> more work in the Hub <br/> context lost from logging

Hopefully this clears up any misunderstanding.

**Comment by zachlatta** [comment]
I'd personally opt for a combination between option 1 and option 3. I think
everything sent through the error channel should make it to the log, but
the developer implementing a module should have access to log arbitrary
text (perhaps to more verbosity than what they'd want to send to the user).

Thoughts?

On Wed, Aug 19, 2015 at 8:12 PM, Benjamin Landers <notifications@github.com>
wrote:

> I think I may not have been clear enough. For any error that hit the
> channel, Logrus should have already been called. So it wouldn't really make
> sense to pipe it to Logrus.
>
> To clarify:
>
> Option 1 (raw error channel)
> module => Logrus
>       L=> error channel => Hub => client
>
> Option 2 (Logrus hook)
> module => Logrus => error channel => Hub => client
>
> Option 3 (error channel that logs)s
> module =>  error channel => Hub => client
>                                L=> Logrus
>
> Option Pro Con 1 simple implementation in hub
> easy testing modules messy passing the error channel around
> messy implementation in modules 2 very clean implementation in modules awkward
> design 3 easy testing modules messy passing the error channel around
> more work in the Hub
> context lost from logging
>
> Hopefully this clears up any misunderstanding.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/maestro/issues/27#issuecomment-132871166>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by TheThirdOne** [comment]
I don't see what the point of logging things sent through the error channel. The module could just log the error independently with proper metadata that wouldn't need to be send to the user.

**Comment by zachlatta** [comment]
I think it may be helpful, even if just for the sake of seeing the errors that users are getting in the logs.

**Comment by jkwok91** [comment]
Closing because this repo is being deprecated
