### ISSUE TITLE
Update MaestroJS Client

### ISSUE THREAD

**Issue by paked** [hackclub/maestro#28]
We discussed updating JS library the on a call today. Obviously we won't be getting this done anytime soon. I wrote a basic prototype of a proposed update for @jonleung's first workshop.

https://gist.github.com/paked/9b00f4baf684d00d338f

edit: I wrote this while being distracted... I will fix up later

/ cc: @zachlatta @TheThirdOne @jonleung

**Comment by zachlatta** [comment]
Any updates on this?

On Thu, Sep 10, 2015 at 11:01 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> We discussed updating JS library the on a call today. Obviously we won't
> be getting this done anytime soon. I wrote a basic prototype of a proposed
> update for @jonleung <https://github.com/jonleung>'s first workshop.
>
> https://gist.github.com/paked/9b00f4baf684d00d338f
>
> / cc: @zachlatta <https://github.com/zachlatta> @TheThirdOne
> <https://github.com/TheThirdOne> @jonleung <https://github.com/jonleung>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/maestro/issues/28>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, this is what I wrote for the client side Twilio library.

@TheThirdOne, I'd love your eyes on this code! See https://github.com/hackedu/hackedu/tree/74b607cf93d15f0af6e9e3e5de7f6863fb05030a/playbook/workshops/twilio/twilio-basic.js

**Comment by TheThirdOne** [comment]
@jonleung, that is a lot of code/functions; how much of it are you using / planning to use?

I can definitely make maestro more like that though.

**Comment by jkwok91** [comment]
Closing because this repo is being deprecated
