### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by zachlatta** [hackclub/maestro#29]
Since we're no longer using this repository, let's go ahead and deprecate it.

To deprecate it:

- Add a `[DEPRECATED]` prefix to the repository description
- Modify README saying that this repository is deprecated and no longer maintained
- Close all existing issues
- Disable issues on the GitHub repo

**Comment by jkwok91** [comment]
Do I have permission to do all of the above things?

**Comment by zachlatta** [comment]
You should!

On Tue, Mar 8, 2016 at 1:06 PM, JESSICA <notifications@github.com> wrote:

> Do I have permission to do all of the above things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/maestro/issues/29#issuecomment-193966548>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Let me know if you don't and I can give you permission.


On Tue, Mar 8, 2016 at 1:06 PM, Zach Latta <zach@zachlatta.com> wrote:

> You should!
>
> On Tue, Mar 8, 2016 at 1:06 PM, JESSICA <notifications@github.com> wrote:
>
>> Do I have permission to do all of the above things?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/maestro/issues/29#issuecomment-193966548>.
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Give permission.

**Comment by zachlatta** [comment]
What do you need permission for? You have permission to write to the repo.

On Tue, Mar 8, 2016 at 1:06 PM, JESSICA <notifications@github.com> wrote:

> Give permission.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/maestro/issues/29#issuecomment-193966715>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Doing this. Closing this issue.
